AWSTemplateFormatVersion: "2010-09-09"

Description: main 

Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc/vpc.yml
      Parameters:
        TagName : "VPC"
  PublicSubnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc/subnet/public.yml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
  PrivateSubnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc/subnet/private.yml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
  # EC2:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ec2/ec2.yml
  #     Parameters:
  #       VPC: !GetAtt VPC.Outputs.VPCID
  #       KeyName: hogehoge
  #       Subnet: !GetAtt PublicSubnet.Outputs.SubnetID