AWSTemplateFormatVersion: '2010-09-09'

Description: 'Public Subnet for nesting'

Parameters:
  AZ:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a
  TagName:
    Type: String
    Default: "Public Subnet for nesting"
  VPC:
    Type: AWS::EC2::VPC::Id

Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Ref AZ
      VpcId: !Ref VPC
      CidrBlock: 10.1.2.0/24
      Tags:
        - Key: Name
          Value: !Ref TagName
  InternetGateway: 
    Type: "AWS::EC2::InternetGateway"
    Properties: 
      Tags: 
        - Key: Name
          Value: !Ref TagName
  InternetGatewayAttachment: 
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC 
  RouteTable: 
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Ref TagName
  Route: 
    Type: "AWS::EC2::Route"
    Properties: 
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway 
  RouteTableAssociation: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

Outputs:
  SubnetID: 
    Value: !Ref PublicSubnet